### ISSUE TITLE
vars have too strong a scope

### ISSUE THREAD

**Issue by ScarabMonkey** [stancel/add-job-to-bareos-director#1]
As you have those vars in role/vars/main.yml they have a very high precedence (15) and actually override anything a user tries to put in their playbook or group_vars - as explained here:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

I would rather have expected those vars to be set in defaults/main.yml where you do have some already...

This means your example usage in the README does not work.

**Comment by stancel** [comment]
Thanks @ScarabMonkey. I know that it may seem strange but I did it this way intentionally based on a variable strategy I came up with and use that makes it fast for me to build my playbooks. Here is a [link to one of my playbook templates](https://github.com/stancel/digital-ocean-suitecrm) where you can see an example of what I mean. 

The goal was to narrow everything down to one or two key variable files only for playbooks where I use those roles. I essentially copy the vars/main.yml content from each of my roles used in a given playbook and then assemble everything into a playbook level vars file called vars/all_vars.yml which is then referenced from the command line when calling the playbook (see the README in the playbook example). 

I did study the variable precedence levels before coming up with my variable strategy / way of doing it, however I decided that I wanted to narrow all of the key applicable variables down to one or two playbook level files and structuring my roles this way makes it easier and faster for me to assemble the playbooks when I need to. I try to come back to these playbooks infrequently and structuring it this way saves me time by keeping everything key in a central place that allows me to find and adjust it quickly. I understand that it does not conform to how others may use or setup their playbooks, but I personally feel that Ansible is a little too flexible here and just came up with an opinionated way to structure my variables for roles and playbooks that has worked well for me and my company. I will review and update the README as soon as I get a chance to correct any incorrect examples or other information. Thanks for letting me know.
